# Generated by Django 6.1 on 2026-08-26 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Audio', 'Audio'), ('Computers', 'Computers'), ('Wearables', 'Wearables'), ('Home Appliances', 'Home Appliances')], default='Electronics', max_length=100)),
                ('star_rating', models.DecimalField(decimal_places=2, help_text='Average Amazon star rating (1.00 - 5.00)', max_digits=3)),
                ('pris_score', models.DecimalField(decimal_places=2, help_text='VADER mean compound score normalized (-1.00 to +1.00)', max_digits=3)),
                ('ai_summary', models.TextField(help_text='Aggregated thematic summary derived from extracted review topics')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AspectSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(help_text='Extracted aspect / topic cluster name', max_length=100)),
                ('vader_compound', models.FloatField(help_text='VADER compound polarity (-1.0 to 1.0)')),
                ('positive_pct', models.PositiveSmallIntegerField(default=0, help_text='Percentage of positive opinions')),
                ('neutral_pct', models.PositiveSmallIntegerField(default=0, help_text='Percentage of neutral opinions')),
                ('negative_pct', models.PositiveSmallIntegerField(default=0, help_text='Percentage of negative opinions')),
                ('sample_sentence', models.TextField(blank=True, help_text='Representative review sentence for aspect drill-down', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='api.product')),
            ],
        ),
    ]
